### PR TITLE
3dviewer -  tests and docs

### PR DESCRIPTION
**Pull request by FedeClaudi**
just added bare bones tests and docs to the 3d viewer.

If either of you has experience with writing tests for pyqt5 apps I could use some help..

----

The travis tests will keep failing until the dev branch of brainrender is published, which will be after brainglobe's release

### CODE REVIEW

**Comment by adamltyson** [comment]
> If either of you has experience with writing tests for pyqt5 apps I could use some help.

Afraid I don't. Napari has good code coverage though. Their tests look relatively easy to understand.

**Comment by FedeClaudi** [comment]
thanks, I can test basic stuff but I can't figure out how to "click" on the tree to test adding a mesh. The only solution I can find would be to have a hidden button somewhere to "click" on and have that do what I need, but it's not very elegant.

**Comment by vigji** [comment]
I don't think there is a way of clicking, I would just invoke the callback function from the button, or to manually (in a line) set the value of the pyqt stuff that code for the tree item to "set" or whatever attribute is changed?

**Comment by FedeClaudi** [comment]
`pytest-qt` has a bot that allows you to simulate clicks, but the docs are crap and can only see how to click on buttons..

**Comment by vigji** [comment]
Too bad! But yes, I guess that invoking the `treeView.clicked` should be enough no?

**Pull request merged**
